name: Test Run

on:
  workflow_dispatch:
    python-version:
      description: 'Python Version'
      required: true
      default: '3.9'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "${{ github.event.inputs.python-version }}"
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry env use python
        poetry install
        poetry run pip list
    - name: Build servicex file
      run: |
        echo "api_endpoints:" > servicex.yaml
        echo "  - name: xaod_r1" >> servicex.yaml
        echo "    endpoint: https://forkit" >> servicex.yaml
        echo "    type: xaod" >> servicex.yaml
        echo "    token: 1234" >> servicex.yaml
    - name: Build the jupyter Book
      run: |
        poetry run jupyter-book clean --all ./book
        poetry run jupyter-book build -W --keep-going --all ./book
    - name: Archive the log files from the run
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: jupyter-book-logs
        path: book/_build/html/reports
